<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.tahopen</groupId>
    <artifactId>tahopen-ce-jar-parent-pom</artifactId>
    <version>0.1.0.0</version>
  </parent>
  <groupId>org.tahopen</groupId>
  <artifactId>tahopen-application-launcher</artifactId>
  <version>0.1.0.0</version>
  <name>Tahopen Application Launcher</name>
  <description>A Tahopen Application Launcher</description>
  
  <licenses>
    <license>
      <name>GNU Lesser General Public License, Version 2.1</name>
      <url>https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt</url>
      <distribution>repo</distribution>
      <comments></comments>
    </license>
  </licenses>

  <scm>
    <connection>scm:git:git://github.com/tahopen/tahopen-application-launcher.git</connection>
    <developerConnection>scm:git:git@github.com:tahopen/tahopen-application-launcher.git</developerConnection>
    <url>https://github.com/tahopen/tahopen-application-launcher</url>
  </scm>  

  <properties>
    <mockito-all.version>1.9.5</mockito-all.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-all</artifactId>
      <version>${mockito-all.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  
  <build>
    <plugins>
    
      <!-- Generate java docs -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.2.0</version>
        <executions>
          <execution>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- sign key gpg--> 
<!-- 
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-gpg-plugin</artifactId>
        <version>3.0.1</version>
        <executions>
          <execution>
            <goals>
              <goal>sign</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
-->
      <!-- publish to Maven Central --> 
<!--     
      <plugin>
         <groupId>org.sonatype.central</groupId>
         <artifactId>central-publishing-maven-plugin</artifactId>
         <version>0.6.0</version>
         <extensions>true</extensions>
         <configuration>
           <publishingServerId>maven-central-snapshots</publishingServerId>
         </configuration>
      </plugin>    
-->
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <mainClass>org.pentaho.commons.launcher.Launcher</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>

    </plugins>
  </build>

  <organization>
    <name>Tahopen Project</name>
    <url>http://www.tahopen.org</url>
  </organization>

  <developers>
    <developer>
      <name>Tahopen Build Team</name>
      <email>marcio@tahopen.org</email>
      <roles>
        <role>creator</role>
        <role>maintainer</role>
      </roles>
    </developer>
  </developers>

  <distributionManagement>

     <repository>
       <id>ossrh</id>
       <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
     </repository>
    
     <snapshotRepository>
       <id>ossrh</id>
       <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
     </snapshotRepository>
    
  </distributionManagement>  
  
</project>
